"""Austial -- a NestJS-inspired, batteries-included web framework for Python,
built on top of FastAPI.

Quickstart::

    from austial import Module, Controller, Get, Injectable, AustialFactory

Most day-to-day symbols (decorators, exceptions, guards, etc.) are re-exported
here for convenience, mirroring how ``@nestjs/common`` re-exports everything
Nest apps need. Deeper framework internals live in ``austial.core``,
``austial.config``, ``austial.database``, ``austial.terminus``,
``austial.testing`` and ``austial.cli``.
"""
from austial.common import (
    AllExceptionsFilter,
    ArgumentMetadata,
    ArgumentsHost,
    BadRequestException,
    Body,
    CallHandler,
    CanActivate,
    Catch,
    ConflictException,
    Controller,
    Delete,
    ExceptionFilter,
    ExecutionContext,
    ForbiddenException,
    Get,
    Global,
    Head,
    Header,
    Headers,
    HttpCode,
    HttpException,
    Inject,
    Injectable,
    InternalServerErrorException,
    LoggingMiddleware,
    Logger,
    MethodNotAllowedException,
    MiddlewareConsumer,
    Module,
    NestInterceptor,
    NestMiddleware,
    NotFoundException,
    NotImplementedException,
    Options,
    Optional_,
    Param,
    Patch,
    PipeTransform,
    Post,
    Put,
    Query,
    Req,
    Res,
    Scope,
    ServiceUnavailableException,
    TooManyRequestsException,
    TransformInterceptor,
    UnauthorizedException,
    UnprocessableEntityException,
    UseFilters,
    UseGuards,
    UseInterceptors,
    UsePipes,
    ValidationPipe,
)
from austial.core import DynamicModule, Reflector
from austial.core.app import AustialApplication
from austial.core.factory import AustialFactory

__version__ = "0.1.0"

__all__ = [
    "AllExceptionsFilter",
    "ArgumentMetadata",
    "ArgumentsHost",
    "AustialApplication",
    "AustialFactory",
    "BadRequestException",
    "Body",
    "CallHandler",
    "CanActivate",
    "Catch",
    "ConflictException",
    "Controller",
    "Delete",
    "DynamicModule",
    "ExceptionFilter",
    "ExecutionContext",
    "ForbiddenException",
    "Get",
    "Global",
    "Head",
    "Header",
    "Headers",
    "HttpCode",
    "HttpException",
    "Inject",
    "Injectable",
    "InternalServerErrorException",
    "Logger",
    "LoggingMiddleware",
    "MethodNotAllowedException",
    "MiddlewareConsumer",
    "Module",
    "NestInterceptor",
    "NestMiddleware",
    "NotFoundException",
    "NotImplementedException",
    "Options",
    "Optional_",
    "Param",
    "Patch",
    "PipeTransform",
    "Post",
    "Put",
    "Query",
    "Reflector",
    "Req",
    "Res",
    "Scope",
    "ServiceUnavailableException",
    "TooManyRequestsException",
    "TransformInterceptor",
    "UnauthorizedException",
    "UnprocessableEntityException",
    "UseFilters",
    "UseGuards",
    "UseInterceptors",
    "UsePipes",
    "ValidationPipe",
]
